services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
       - postgres-data:/var/lib/postgresql/data
    ports:
      - $DB_PORT:$DB_PORT
    restart: unless-stopped
volumes:
  postgres-data: