include:
  - docker-compose-redis.yaml
  - docker-compose-postgres.yaml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres