include:
  - docker-compose-redis.yaml
  - docker-compose-postgres.yaml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /src
          ignore: 
            - node_modules
    depends_on:
      - redis
      - postgres