import { ColumnType, Generated, Insertable, Selectable, Updateable } from 'kysely'
import { UUID } from 'crypto';

export interface Database {
	user: UserTable;
}

export interface UserTable {
	// Columns that are generated by the database should be marked
	// using the `Generated` type. This way they are automatically
	// made optional in inserts and updates.
	id: Generated<UUID>;
	email: string;
	username: string;
	salt: string;
	password: string;
	created_at: ColumnType<Date, string | undefined, never>;
}

// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.

export type CreateUser = Insertable<UserTable>;
export type UpdateUser = Updateable<UserTable>;
export type SelectUser = Selectable<UserTable>;